language: c
install: true
before_script:
 - wget https://github.com/ireader/sdk/archive/master.zip -O /tmp/sdk.zip
 - unzip /tmp/sdk.zip
 - echo $PWD
 - mv sdk-master ../sdk

env:
  global:
   - secure: "EDSZDN0TGNznJlTy+xqBYSqNSXMzLg6K0+CNmfkstQ+yBzAGA7cf8kGy5PUei8DMh5I3/2BV6mJsKmjaIVDcE4hm4W6ztUIXyFK3dRTxjkVDtEciTefJgaFNh0xzElHi+yGHGW6zYfDa09RqCv6IgIHlEHy+B3WEei/h/Z61I11yD18DdhlEZss7aMEQYci8jjBKgnUGpgyuZxJCt/T4MCZ5b9NmgO4dE+QcjXZPD8KD6lC/gtkpklsm88KvsorxjjjWNrOyalq2sW0I1c90ykyXpONgOj7beIt/qMQxUGOGvx3x1UUI9gcbr4zgmOuQhHsMQV6SAifEr8Rkz+Y7R3+Gu78E4tCiVRMM6kJefcwFtGLuUZfEfiOXT9ihkEp65fiXzi8Pw0/HPDt93167qsuSpQyQE8I78KPjM5z/ncAXMd3NtebZ50FCZSliFBzoYMZxeiYDCUbGuCNzNP7Tpjg7JkRFb3XjboRcZzeaCv3WyhnDGloCMdh2gjKnD7Z/9tMg5B1hf3vjg07x90lLAZP057c8+BJK+5PraDlAovuiH/x/iunBp73gQX7tnKrnnivM4nolsxYdMFdmjcgIhEDVfBS1XkefZI888l7uDp+pki26GfLFy9ToInMDt0a/vBHfJpR8vhIfp5LOGhjuXxF62mBM9E1/hstRK5ACJ+o="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ireader/media-server"
      description: "media-server"
    notification_email: tao3@outlook.com
    build_command: "make"
    branch_pattern: master

script: make
